PIN_ROOT ?= /home/stefanos/pin-3.27-98718-gbeaa5d51e-gcc-linux
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
